# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!({ name: "Will Wheaton", password_digest: "password", email: "wheaton@example.com" })
User.create!({ name: "Matt Mercer", password_digest: "password", email: "mercer@example.com" })
User.create!({ name: "Felicia Day", password_digest: "password", email: "day@example.com" })

Character.create!({ user_id: 1, name: "Fiego", level: 1, character_class_id: 2, speciality: "nuker", nuke_score: 0, cc_score: 0, utility_score: 0, face_score: 0 })
Character.create!({ user_id: 2, name: "Bryssais", level: 1, character_class_id: 3, speciality: "utility", nuke_score: 0, cc_score: 0, utility_score: 0, face_score: 0 })
Character.create!({ user_id: 3, name: "La Roux", level: 1, character_class_id: 3, speciality: "none", nuke_score: 0, cc_score: 0, utility_score: 0, face_score: 0 })
Character.create!({ user_id: 1, name: "Tully", level: 1, character_class_id: 1, speciality: "the face", nuke_score: 0, cc_score: 0, utility_score: 0, face_score: 0 })
Character.create!({ user_id: 2, name: "Jenevra", level: 1, character_class_id: 2, speciality: "crowd control", nuke_score: 0, cc_score: 0, utility_score: 0, face_score: 0 })

CharacterClass.create!({ character_class: "sorcerer", character_class_id: 1 })
CharacterClass.create!({ character_class: "warlock", character_class_id: 2 })
CharacterClass.create!({ character_class: "wizard", character_class_id: 3 })

CharacterSpell.create!({ character_id: 1, spell_id: 1 })
CharacterSpell.create!({ character_id: 1, spell_id: 8 })
CharacterSpell.create!({ character_id: 1, spell_id: 12 })
CharacterSpell.create!({ character_id: 2, spell_id: 5 })
CharacterSpell.create!({ character_id: 2, spell_id: 6 })
CharacterSpell.create!({ character_id: 2, spell_id: 7 })
CharacterSpell.create!({ character_id: 2, spell_id: 9 })
CharacterSpell.create!({ character_id: 2, spell_id: 10 })
CharacterSpell.create!({ character_id: 3, spell_id: 2 })
CharacterSpell.create!({ character_id: 3, spell_id: 4 })
CharacterSpell.create!({ character_id: 3, spell_id: 8 })
CharacterSpell.create!({ character_id: 3, spell_id: 11 })
CharacterSpell.create!({ character_id: 3, spell_id: 12 })
CharacterSpell.create!({ character_id: 4, spell_id: 3 })
CharacterSpell.create!({ character_id: 4, spell_id: 5 })
CharacterSpell.create!({ character_id: 4, spell_id: 6 })
CharacterSpell.create!({ character_id: 4, spell_id: 7 })
CharacterSpell.create!({ character_id: 4, spell_id: 9 })
CharacterSpell.create!({ character_id: 4, spell_id: 10 })
CharacterSpell.create!({ character_id: 5, spell_id: 3 })
CharacterSpell.create!({ character_id: 5, spell_id: 5 })
CharacterSpell.create!({ character_id: 5, spell_id: 10 })

CharacterClassSpell.create!({ character_class_id: 1, spell_id: 2 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 3 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 5 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 6 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 7 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 9 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 10 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 11 })
CharacterClassSpell.create!({ character_class_id: 1, spell_id: 12 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 1 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 3 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 5 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 8 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 9 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 10 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 11 })
CharacterClassSpell.create!({ character_class_id: 2, spell_id: 12 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 2 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 3 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 4 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 5 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 6 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 7 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 8 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 9 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 10 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 11 })
CharacterClassSpell.create!({ character_class_id: 3, spell_id: 12 })

Spell.create!({ name: "eldritch blast", nuker_score: 5, cc_score: 3, utility_score: 0, face_score: 0, level: 0 })
Spell.create!({ name: "fire bolt", nuker_score: 5, cc_score: 3, utility_score: 1, face_score: 0, level: 0 })
Spell.create!({ name: "friends", nuker_score: 0, cc_score: 3, utility_score: 4, face_score: 5, level: 0 })
Spell.create!({ name: "gust", nuker_score: 2, cc_score: 3, utility_score: 0, face_score: 0, level: 0 })
Spell.create!({ name: "mage hand", nuker_score: 2, cc_score: 3, utility_score: 5, face_score: 0, level: 0 })
Spell.create!({ name: "message", nuker_score: 0, cc_score: 1, utility_score: 5, face_score: 4, level: 0 })
Spell.create!({ name: "mold earth", nuker_score: 1, cc_score: 2, utility_score: 5, face_score: 0, level: 0 })
Spell.create!({ name: "toll the dead", nuker_score: 4, cc_score: 3, utility_score: 1, face_score: 0, level: 0 })
Spell.create!({ name: "charm person", nuker_score: 0, cc_score: 3, utility_score: 4, face_score: 5, level: 1 })
Spell.create!({ name: "comprehend language", nuker_score: 0, cc_score: 0, utility_score: 5, face_score: 4, level: 1 })
Spell.create!({ name: "sleep", nuker_score: 0, cc_score: 5, utility_score: 3, face_score: 0, level: 1 })
Spell.create!({ name: "witch bolt", nuker_score: 5, cc_score: 3, utility_score: 0, face_score: 0, level: 1 })
